const lineasDePrestamos = [
  {
    id: 1,
    reglamentacion: 245,
    nombre: "descuento de cheques de pago diferido",
    plazo1: 45,
    plazo2: 90,
    plazo3: 180,
    plazo4: 270,
    tasa1: 94,
    tasa2: 98,
    tasa3: 108,
    tasa4: 115,
    usuario: "indistinto",
    destino: "indistinto",
    montoMinimo: 50000,
    montoMaximo: "indistinto",
  },
  {
    id: 2,
    reglamentacion: 629,
    nombre: "prestamos a microempresas para desarrolo productivo",
    plazo1: 24,
    tasa1: 63,
    usuario: "micro",
    destino: "capital de trabajo",
    montoMinimo: 100000,
    montoMaximo: 4000000,
  },
  {
    id: 3,
    reglamentacion: 750,
    nombre: "prestamos a pequeñas empresas para inversion productiva",
    plazo1: 60,
    tasa1: 97,
    usuario: "pyme",
    destino: "inversion",
    montoMinimo: 5000000,
    montoMaximo: 80000000,
  },
];

const lineasDeInversion = [
  {
    id: 1,
    imagen: "PF.png",
    nombre: "plazo fijo",
    usuario: "indistinto",
    tasa1: 118,
    montoMinimo: 500,
    montoMaximo: 10000000000,
    perfil: "conservador",
  },
  {
    id: 2,
    nombre: "fondo común de inversión",
    imagen: "assets/FCI.png",
    usuario: "indistinto",
    tasa1: 135,
    montoMinimo: 5000,
    montoMaximo: 1000000000,
    perfil: "flexible",
  },
];
