const lineasDePrestamos = [
  {
    id: 1,
    reglamentacion: 245,
    nombre: "descuento de cheques de pago diferido",
    plazo: [ 45, 90, 180, 270 ],
    tasa: [ 94, 98, 108, 115] ,
    usuario: "indistinto",
    destino: "indistinto",
    montoMinimo: 50000,
    montoMaximo: "indistinto",
  },
  {
    id: 2,
    reglamentacion: 629,
    nombre: "prestamos a microempresas para desarrolo productivo",
    plazo: 24,
    tasa: 63,
    usuario: "micro",
    destino: "capital de trabajo",
    montoMinimo: 100000,
    montoMaximo: 4000000,
  },
  {
    id: 3,
    reglamentacion: 750,
    nombre: "prestamos a pequeñas empresas para inversion productiva",
    plazo: 60,
    tasa: 97,
    usuario: "pyme",
    destino: "inversion",
    montoMinimo: 5000000,
    montoMaximo: 80000000,
  },
];

const lineasDeInversion = [
  {
    id: 1,
    imagen: "assets/PF.png",
    nombre: "plazo fijo",
    usuario: "indistinto",
    tasa: 118,
    montoMinimo: 500,
    montoMaximo: 10000000000,
    perfil: "conservador",
  },
  {
    id: 2,
    nombre: "fondo común de inversión",
    imagen: "assets/FCI.png",
    usuario: "indistinto",
    tasa: 135,
    montoMinimo: 5000,
    montoMaximo: 1000000000,
    perfil: "flexible",
  },
];
